<?php

/**
 * @file
 * Contains signalzen.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function signalzen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.signalzen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides configurable SignalZen live chat widget') . '</p>';
      return $output;

    default:
  }
}
