<?php

/**
 * @file
 * Contains signalzen.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function signalzen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.signalzen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides configurable SignalZen live chat widget') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function signalzen_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\signalzen\SignalZenWidgetManagerInterface $widget_manager */
  $widget_manager = \Drupal::service('signalzen.widget.manager');

  $attachments['#attached']['drupalSettings']['signalZen'] = $widget_manager->getWidgetConfiguration();
  $attachments['#attached']['library'][] = 'signalzen/widget';
}
