<?php

/**
 * @file
 * Contains signalzen.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function signalzen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.signalzen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SignalZen is a live chat solution for your website which enables you to engage and talk to your website visitors.');
      $output .= '<br />';
      $output .= t('We provide you with simplicity oriented service which includes such features as <a href=":slack" target="_blank">Slack</a> integration and <a href=":docs" target="_blank">API</a> to work with your accumulated data sent by your website visitors.', [':slack' => 'https://slack.com', ':docs' => 'http://docs.signalzen.com/']);
      $output .= '<br />';
      $output .= t('Please read more at <a href=":homepage" target="_blank">signalzen.com</a>.', [':homepage' => 'https://signalzen.com']) . '</p>';
      $output .= '<h3>' . t('Integration with your website') . '</h3>';
      $output .= '<p>' . t('This Wordpress plugin should make the integration with SignalZen incredibly easy and fast.');
      $output .= '<br />';
      $output .= t('However, before proceeding, make sure you have <a href=":signup" target="_blank">setup an account</a>.', [':signup' => 'https://portal.signalzen.com/sign-up']) . '</p>';
      $output .= '<p>' . t('To enable SignalZen chat widget on your website, you just need to enter your <strong>Public Token</strong> which you can find in the <strong>Integration page</strong> while logged in to your account at <a href=":homepage" target="_blank">signalzen.com</a>.', [':homepage' => 'https://signalzen.com/']);
      $output .= '<br />';
      $output .= t('Once you enter your Public Token here and submit the form, your website will contain our live chat widget and you can start talking to them by using our portal or <a href=":slack" target="_blank">Slack</a> if you choose to integrate with it also.', [':slack' => 'https://slack.com']) . '</p>';
      $output .= '<p>Happy chatting!</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Attach SignalZen live chat javascript libraries and initialize widget.
 */
function signalzen_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\signalzen\SignalZenWidgetManagerInterface $widget_manager */
  $widget_manager = \Drupal::service('signalzen.widget.manager');

  if ($widget_manager->canUserUseWidget() && $widget_manager->displayOnRoute()) {
    $attachments['#attached']['drupalSettings']['signalZen'] = $widget_manager->getWidgetConfiguration();
    $attachments['#attached']['library'][] = 'signalzen/widget';
  }
}
